title: An Introduction 
author: ks_joanna
email: jche@uwo.ca
description: > # this means to ignore newlines until "baseurl:"
  This site is still under construction.

# social links
twitter_username: --> jche632 # DO NOT include the @ character, or else the build will fail!
github_username: --> ksjoanna # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
